version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: oko-ui
        restart: unless-stopped
        ports:
            - '3000:80'
        environment:
            - NODE_ENV=production
        networks:
            - oko-network

networks:
    oko-network:
        driver: bridge
