/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ResourcesIndexImport } from './routes/resources/index'
import { Route as ChannelsIndexImport } from './routes/channels/index'
import { Route as ResourcesCreateImport } from './routes/resources/create'
import { Route as ChannelsCreateImport } from './routes/channels/create'
import { Route as AuthAuthImport } from './routes/auth/_auth'
import { Route as ResourcesResourceIdIndexImport } from './routes/resources/$resourceId/index'
import { Route as ChannelsChannelIdIndexImport } from './routes/channels/$channelId/index'
import { Route as ResourcesResourceIdEditImport } from './routes/resources/$resourceId/edit'
import { Route as ChannelsChannelIdEditImport } from './routes/channels/$channelId/edit'
import { Route as AuthAuthRestoreImport } from './routes/auth/_auth.restore'
import { Route as AuthAuthLoginImport } from './routes/auth/_auth.login'
import { Route as ResourcesResourceIdSnapshotsIndexImport } from './routes/resources/$resourceId/snapshots/index'
import { Route as ResourcesResourceIdEventsIndexImport } from './routes/resources/$resourceId/events/index'
import { Route as ResourcesResourceIdSnapshotsSnapshotIdIndexImport } from './routes/resources/$resourceId/snapshots/$snapshotId/index'
import { Route as ResourcesResourceIdEventsEventIdIndexImport } from './routes/resources/$resourceId/events/$eventId/index'

// Create Virtual Routes

const AuthImport = createFileRoute('/auth')()

// Create/Update Routes

const AuthRoute = AuthImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ResourcesIndexRoute = ResourcesIndexImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => rootRoute,
} as any)

const ChannelsIndexRoute = ChannelsIndexImport.update({
  id: '/channels/',
  path: '/channels/',
  getParentRoute: () => rootRoute,
} as any)

const ResourcesCreateRoute = ResourcesCreateImport.update({
  id: '/resources/create',
  path: '/resources/create',
  getParentRoute: () => rootRoute,
} as any)

const ChannelsCreateRoute = ChannelsCreateImport.update({
  id: '/channels/create',
  path: '/channels/create',
  getParentRoute: () => rootRoute,
} as any)

const AuthAuthRoute = AuthAuthImport.update({
  id: '/_auth',
  getParentRoute: () => AuthRoute,
} as any)

const ResourcesResourceIdIndexRoute = ResourcesResourceIdIndexImport.update({
  id: '/resources/$resourceId/',
  path: '/resources/$resourceId/',
  getParentRoute: () => rootRoute,
} as any)

const ChannelsChannelIdIndexRoute = ChannelsChannelIdIndexImport.update({
  id: '/channels/$channelId/',
  path: '/channels/$channelId/',
  getParentRoute: () => rootRoute,
} as any)

const ResourcesResourceIdEditRoute = ResourcesResourceIdEditImport.update({
  id: '/resources/$resourceId/edit',
  path: '/resources/$resourceId/edit',
  getParentRoute: () => rootRoute,
} as any)

const ChannelsChannelIdEditRoute = ChannelsChannelIdEditImport.update({
  id: '/channels/$channelId/edit',
  path: '/channels/$channelId/edit',
  getParentRoute: () => rootRoute,
} as any)

const AuthAuthRestoreRoute = AuthAuthRestoreImport.update({
  id: '/restore',
  path: '/restore',
  getParentRoute: () => AuthAuthRoute,
} as any)

const AuthAuthLoginRoute = AuthAuthLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthAuthRoute,
} as any)

const ResourcesResourceIdSnapshotsIndexRoute =
  ResourcesResourceIdSnapshotsIndexImport.update({
    id: '/resources/$resourceId/snapshots/',
    path: '/resources/$resourceId/snapshots/',
    getParentRoute: () => rootRoute,
  } as any)

const ResourcesResourceIdEventsIndexRoute =
  ResourcesResourceIdEventsIndexImport.update({
    id: '/resources/$resourceId/events/',
    path: '/resources/$resourceId/events/',
    getParentRoute: () => rootRoute,
  } as any)

const ResourcesResourceIdSnapshotsSnapshotIdIndexRoute =
  ResourcesResourceIdSnapshotsSnapshotIdIndexImport.update({
    id: '/resources/$resourceId/snapshots/$snapshotId/',
    path: '/resources/$resourceId/snapshots/$snapshotId/',
    getParentRoute: () => rootRoute,
  } as any)

const ResourcesResourceIdEventsEventIdIndexRoute =
  ResourcesResourceIdEventsEventIdIndexImport.update({
    id: '/resources/$resourceId/events/$eventId/',
    path: '/resources/$resourceId/events/$eventId/',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/auth/_auth': {
      id: '/auth/_auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthAuthImport
      parentRoute: typeof AuthRoute
    }
    '/channels/create': {
      id: '/channels/create'
      path: '/channels/create'
      fullPath: '/channels/create'
      preLoaderRoute: typeof ChannelsCreateImport
      parentRoute: typeof rootRoute
    }
    '/resources/create': {
      id: '/resources/create'
      path: '/resources/create'
      fullPath: '/resources/create'
      preLoaderRoute: typeof ResourcesCreateImport
      parentRoute: typeof rootRoute
    }
    '/channels/': {
      id: '/channels/'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof ChannelsIndexImport
      parentRoute: typeof rootRoute
    }
    '/resources/': {
      id: '/resources/'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesIndexImport
      parentRoute: typeof rootRoute
    }
    '/auth/_auth/login': {
      id: '/auth/_auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthAuthLoginImport
      parentRoute: typeof AuthAuthImport
    }
    '/auth/_auth/restore': {
      id: '/auth/_auth/restore'
      path: '/restore'
      fullPath: '/auth/restore'
      preLoaderRoute: typeof AuthAuthRestoreImport
      parentRoute: typeof AuthAuthImport
    }
    '/channels/$channelId/edit': {
      id: '/channels/$channelId/edit'
      path: '/channels/$channelId/edit'
      fullPath: '/channels/$channelId/edit'
      preLoaderRoute: typeof ChannelsChannelIdEditImport
      parentRoute: typeof rootRoute
    }
    '/resources/$resourceId/edit': {
      id: '/resources/$resourceId/edit'
      path: '/resources/$resourceId/edit'
      fullPath: '/resources/$resourceId/edit'
      preLoaderRoute: typeof ResourcesResourceIdEditImport
      parentRoute: typeof rootRoute
    }
    '/channels/$channelId/': {
      id: '/channels/$channelId/'
      path: '/channels/$channelId'
      fullPath: '/channels/$channelId'
      preLoaderRoute: typeof ChannelsChannelIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/resources/$resourceId/': {
      id: '/resources/$resourceId/'
      path: '/resources/$resourceId'
      fullPath: '/resources/$resourceId'
      preLoaderRoute: typeof ResourcesResourceIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/resources/$resourceId/events/': {
      id: '/resources/$resourceId/events/'
      path: '/resources/$resourceId/events'
      fullPath: '/resources/$resourceId/events'
      preLoaderRoute: typeof ResourcesResourceIdEventsIndexImport
      parentRoute: typeof rootRoute
    }
    '/resources/$resourceId/snapshots/': {
      id: '/resources/$resourceId/snapshots/'
      path: '/resources/$resourceId/snapshots'
      fullPath: '/resources/$resourceId/snapshots'
      preLoaderRoute: typeof ResourcesResourceIdSnapshotsIndexImport
      parentRoute: typeof rootRoute
    }
    '/resources/$resourceId/events/$eventId/': {
      id: '/resources/$resourceId/events/$eventId/'
      path: '/resources/$resourceId/events/$eventId'
      fullPath: '/resources/$resourceId/events/$eventId'
      preLoaderRoute: typeof ResourcesResourceIdEventsEventIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/resources/$resourceId/snapshots/$snapshotId/': {
      id: '/resources/$resourceId/snapshots/$snapshotId/'
      path: '/resources/$resourceId/snapshots/$snapshotId'
      fullPath: '/resources/$resourceId/snapshots/$snapshotId'
      preLoaderRoute: typeof ResourcesResourceIdSnapshotsSnapshotIdIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface AuthAuthRouteChildren {
  AuthAuthLoginRoute: typeof AuthAuthLoginRoute
  AuthAuthRestoreRoute: typeof AuthAuthRestoreRoute
}

const AuthAuthRouteChildren: AuthAuthRouteChildren = {
  AuthAuthLoginRoute: AuthAuthLoginRoute,
  AuthAuthRestoreRoute: AuthAuthRestoreRoute,
}

const AuthAuthRouteWithChildren = AuthAuthRoute._addFileChildren(
  AuthAuthRouteChildren,
)

interface AuthRouteChildren {
  AuthAuthRoute: typeof AuthAuthRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAuthRoute: AuthAuthRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthAuthRouteWithChildren
  '/channels/create': typeof ChannelsCreateRoute
  '/resources/create': typeof ResourcesCreateRoute
  '/channels': typeof ChannelsIndexRoute
  '/resources': typeof ResourcesIndexRoute
  '/auth/login': typeof AuthAuthLoginRoute
  '/auth/restore': typeof AuthAuthRestoreRoute
  '/channels/$channelId/edit': typeof ChannelsChannelIdEditRoute
  '/resources/$resourceId/edit': typeof ResourcesResourceIdEditRoute
  '/channels/$channelId': typeof ChannelsChannelIdIndexRoute
  '/resources/$resourceId': typeof ResourcesResourceIdIndexRoute
  '/resources/$resourceId/events': typeof ResourcesResourceIdEventsIndexRoute
  '/resources/$resourceId/snapshots': typeof ResourcesResourceIdSnapshotsIndexRoute
  '/resources/$resourceId/events/$eventId': typeof ResourcesResourceIdEventsEventIdIndexRoute
  '/resources/$resourceId/snapshots/$snapshotId': typeof ResourcesResourceIdSnapshotsSnapshotIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthAuthRouteWithChildren
  '/channels/create': typeof ChannelsCreateRoute
  '/resources/create': typeof ResourcesCreateRoute
  '/channels': typeof ChannelsIndexRoute
  '/resources': typeof ResourcesIndexRoute
  '/auth/login': typeof AuthAuthLoginRoute
  '/auth/restore': typeof AuthAuthRestoreRoute
  '/channels/$channelId/edit': typeof ChannelsChannelIdEditRoute
  '/resources/$resourceId/edit': typeof ResourcesResourceIdEditRoute
  '/channels/$channelId': typeof ChannelsChannelIdIndexRoute
  '/resources/$resourceId': typeof ResourcesResourceIdIndexRoute
  '/resources/$resourceId/events': typeof ResourcesResourceIdEventsIndexRoute
  '/resources/$resourceId/snapshots': typeof ResourcesResourceIdSnapshotsIndexRoute
  '/resources/$resourceId/events/$eventId': typeof ResourcesResourceIdEventsEventIdIndexRoute
  '/resources/$resourceId/snapshots/$snapshotId': typeof ResourcesResourceIdSnapshotsSnapshotIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/auth/_auth': typeof AuthAuthRouteWithChildren
  '/channels/create': typeof ChannelsCreateRoute
  '/resources/create': typeof ResourcesCreateRoute
  '/channels/': typeof ChannelsIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/auth/_auth/login': typeof AuthAuthLoginRoute
  '/auth/_auth/restore': typeof AuthAuthRestoreRoute
  '/channels/$channelId/edit': typeof ChannelsChannelIdEditRoute
  '/resources/$resourceId/edit': typeof ResourcesResourceIdEditRoute
  '/channels/$channelId/': typeof ChannelsChannelIdIndexRoute
  '/resources/$resourceId/': typeof ResourcesResourceIdIndexRoute
  '/resources/$resourceId/events/': typeof ResourcesResourceIdEventsIndexRoute
  '/resources/$resourceId/snapshots/': typeof ResourcesResourceIdSnapshotsIndexRoute
  '/resources/$resourceId/events/$eventId/': typeof ResourcesResourceIdEventsEventIdIndexRoute
  '/resources/$resourceId/snapshots/$snapshotId/': typeof ResourcesResourceIdSnapshotsSnapshotIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/channels/create'
    | '/resources/create'
    | '/channels'
    | '/resources'
    | '/auth/login'
    | '/auth/restore'
    | '/channels/$channelId/edit'
    | '/resources/$resourceId/edit'
    | '/channels/$channelId'
    | '/resources/$resourceId'
    | '/resources/$resourceId/events'
    | '/resources/$resourceId/snapshots'
    | '/resources/$resourceId/events/$eventId'
    | '/resources/$resourceId/snapshots/$snapshotId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/channels/create'
    | '/resources/create'
    | '/channels'
    | '/resources'
    | '/auth/login'
    | '/auth/restore'
    | '/channels/$channelId/edit'
    | '/resources/$resourceId/edit'
    | '/channels/$channelId'
    | '/resources/$resourceId'
    | '/resources/$resourceId/events'
    | '/resources/$resourceId/snapshots'
    | '/resources/$resourceId/events/$eventId'
    | '/resources/$resourceId/snapshots/$snapshotId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/auth/_auth'
    | '/channels/create'
    | '/resources/create'
    | '/channels/'
    | '/resources/'
    | '/auth/_auth/login'
    | '/auth/_auth/restore'
    | '/channels/$channelId/edit'
    | '/resources/$resourceId/edit'
    | '/channels/$channelId/'
    | '/resources/$resourceId/'
    | '/resources/$resourceId/events/'
    | '/resources/$resourceId/snapshots/'
    | '/resources/$resourceId/events/$eventId/'
    | '/resources/$resourceId/snapshots/$snapshotId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  ChannelsCreateRoute: typeof ChannelsCreateRoute
  ResourcesCreateRoute: typeof ResourcesCreateRoute
  ChannelsIndexRoute: typeof ChannelsIndexRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
  ChannelsChannelIdEditRoute: typeof ChannelsChannelIdEditRoute
  ResourcesResourceIdEditRoute: typeof ResourcesResourceIdEditRoute
  ChannelsChannelIdIndexRoute: typeof ChannelsChannelIdIndexRoute
  ResourcesResourceIdIndexRoute: typeof ResourcesResourceIdIndexRoute
  ResourcesResourceIdEventsIndexRoute: typeof ResourcesResourceIdEventsIndexRoute
  ResourcesResourceIdSnapshotsIndexRoute: typeof ResourcesResourceIdSnapshotsIndexRoute
  ResourcesResourceIdEventsEventIdIndexRoute: typeof ResourcesResourceIdEventsEventIdIndexRoute
  ResourcesResourceIdSnapshotsSnapshotIdIndexRoute: typeof ResourcesResourceIdSnapshotsSnapshotIdIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  ChannelsCreateRoute: ChannelsCreateRoute,
  ResourcesCreateRoute: ResourcesCreateRoute,
  ChannelsIndexRoute: ChannelsIndexRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
  ChannelsChannelIdEditRoute: ChannelsChannelIdEditRoute,
  ResourcesResourceIdEditRoute: ResourcesResourceIdEditRoute,
  ChannelsChannelIdIndexRoute: ChannelsChannelIdIndexRoute,
  ResourcesResourceIdIndexRoute: ResourcesResourceIdIndexRoute,
  ResourcesResourceIdEventsIndexRoute: ResourcesResourceIdEventsIndexRoute,
  ResourcesResourceIdSnapshotsIndexRoute:
    ResourcesResourceIdSnapshotsIndexRoute,
  ResourcesResourceIdEventsEventIdIndexRoute:
    ResourcesResourceIdEventsEventIdIndexRoute,
  ResourcesResourceIdSnapshotsSnapshotIdIndexRoute:
    ResourcesResourceIdSnapshotsSnapshotIdIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/auth",
        "/channels/create",
        "/resources/create",
        "/channels/",
        "/resources/",
        "/channels/$channelId/edit",
        "/resources/$resourceId/edit",
        "/channels/$channelId/",
        "/resources/$resourceId/",
        "/resources/$resourceId/events/",
        "/resources/$resourceId/snapshots/",
        "/resources/$resourceId/events/$eventId/",
        "/resources/$resourceId/snapshots/$snapshotId/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/auth": {
      "filePath": "auth",
      "children": [
        "/auth/_auth"
      ]
    },
    "/auth/_auth": {
      "filePath": "auth/_auth.tsx",
      "parent": "/auth",
      "children": [
        "/auth/_auth/login",
        "/auth/_auth/restore"
      ]
    },
    "/channels/create": {
      "filePath": "channels/create.tsx"
    },
    "/resources/create": {
      "filePath": "resources/create.tsx"
    },
    "/channels/": {
      "filePath": "channels/index.tsx"
    },
    "/resources/": {
      "filePath": "resources/index.tsx"
    },
    "/auth/_auth/login": {
      "filePath": "auth/_auth.login.tsx",
      "parent": "/auth/_auth"
    },
    "/auth/_auth/restore": {
      "filePath": "auth/_auth.restore.tsx",
      "parent": "/auth/_auth"
    },
    "/channels/$channelId/edit": {
      "filePath": "channels/$channelId/edit.tsx"
    },
    "/resources/$resourceId/edit": {
      "filePath": "resources/$resourceId/edit.tsx"
    },
    "/channels/$channelId/": {
      "filePath": "channels/$channelId/index.tsx"
    },
    "/resources/$resourceId/": {
      "filePath": "resources/$resourceId/index.tsx"
    },
    "/resources/$resourceId/events/": {
      "filePath": "resources/$resourceId/events/index.tsx"
    },
    "/resources/$resourceId/snapshots/": {
      "filePath": "resources/$resourceId/snapshots/index.tsx"
    },
    "/resources/$resourceId/events/$eventId/": {
      "filePath": "resources/$resourceId/events/$eventId/index.tsx"
    },
    "/resources/$resourceId/snapshots/$snapshotId/": {
      "filePath": "resources/$resourceId/snapshots/$snapshotId/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
