name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    verify_files:
        name: Verify Files
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - uses: pnpm/action-setup@v4
              name: Install pnpm
              with:
                  version: 10
                  run_install: false
            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 22
                  cache: 'pnpm'
            - name: Install Packages
              run: pnpm i
            - name: Lint Files
              run: pnpm run lint
            - name: Typecheck
              run: pnpm run typecheck
            - name: Find circular dependencies
              run: pnpm run circular-deps

    tests:
        name: Tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - uses: pnpm/action-setup@v4
              name: Install pnpm
              with:
                  version: 10
                  run_install: false
            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 22
                  cache: 'pnpm'
            - name: Install Packages
              run: pnpm i
            - name: Unit Tests
              run: pnpm run test
