name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    verify_files:
        name: Verify Files
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Install pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: 10
                  run_install: false

            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 22
                  cache: 'pnpm'

            - name: Install Packages
              run: pnpm install

            - name: Lint Files
              run: pnpm run lint

            - name: Typecheck
              run: pnpm run typecheck

            - name: Find circular dependencies
              run: pnpm run circular-deps

    unit-tests:
        name: Unit Tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Install pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: 10
                  run_install: false

            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 22
                  cache: 'pnpm'

            - name: Install Packages
              run: pnpm install

            - name: Unit Tests
              run: pnpm run test:unit

    storybook_tests:
        name: Storybook Tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Install pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: 10
                  run_install: false

            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 22
                  cache: 'pnpm'

            - name: Install Packages
              run: pnpm install

            - name: Install Playwright Browsers
              run: pnpm exec playwright install --with-deps

            - name: Build Storybook Static
              run: pnpm run build-storybook

            - name: Serve Storybook and Run Tests
              run: |
                  pnpm concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
                    "npx http-server storybook-static --port 7009 --silent" \
                    "npx wait-on $PR_PREVIEW_URL && pnpm run test:storybook"
              env:
                  PR_PREVIEW_URL: http://127.0.0.1:7009

    chromatic:
        name: Run Chromatic
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Install pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: 10
                  run_install: false

            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 22
                  cache: 'pnpm'

            - name: Install Packages
              run: pnpm install

            - name: Run Chromatic
              uses: chromaui/action@latest
              with:
                  projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
