name: Main Preview

on:
    push:
        branches: [main]

jobs:
    main:
        name: Build and Deploy
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Install pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: 10
                  run_install: false

            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 22
                  cache: 'pnpm'

            - name: Install Packages
              run: pnpm install

            - name: Build Storybook
              run: pnpm run build-storybook

            - name: Install AWS CLI
              uses: unfor19/install-aws-cli-action@v1
              with:
                  version: 2.22.35
                  arch: amd64

            - name: Upload to S3
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.STORYBOOK_S3_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.STORYBOOK_S3_SECRET_KEY }}
                  AWS_DEFAULT_REGION: ru-central1
                  AWS_EC2_METADATA_DISABLED: true
                  AWS_REQUEST_CHECKSUM_CALCULATION: when_required
                  AWS_RESPONSE_CHECKSUM_VALIDATION: when_required
              run: aws s3 cp static s3://storybook-oko-ui/main/ --endpoint-url=https://storage.yandexcloud.net --recursive
              shell: bash
