name: PR Preview Build

on:
    pull_request:

jobs:
    build:
        name: Build Storybook
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Install pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: 10
                  run_install: false

            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 22
                  cache: 'pnpm'

            - name: Install Packages
              run: pnpm install

            - name: Build Storybook
              run: pnpm run build-storybook

            - name: Create Static Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: static
                  path: ./storybook-static

            - name: Save PR ID
              run: |
                  pr="${{ github.event.pull_request.number }}"
                  echo $pr > ./pr-id.txt
              shell: bash

            - name: Create PR Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: pr
                  path: ./pr-id.txt

            - name: Download Artifacts
              uses: actions/download-artifact@v4
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  run-id: ${{ github.event.workflow_run.id }}
                  path: ./artifacts

            - name: Extract PR Number
              id: pr
              run: |
                  echo "id=$(cat artifacts/pr/pr-id.txt)" >> $GITHUB_OUTPUT
              shell: bash

            - name: Install AWS CLI
              uses: unfor19/install-aws-cli-action@v1
              with:
                  version: 2.22.35
                  arch: amd64

            - name: Upload to S3
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.STORYBOOK_S3_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.STORYBOOK_S3_SECRET_KEY }}
                  AWS_DEFAULT_REGION: ru-central1
                  AWS_EC2_METADATA_DISABLED: true
                  AWS_REQUEST_CHECKSUM_CALCULATION: when_required
                  AWS_RESPONSE_CHECKSUM_VALIDATION: when_required
              run: aws s3 cp artifacts/static s3://storybook-oko-ui/pulls/${{ steps.pr.outputs.id }}/ --endpoint-url=https://storage.yandexcloud.net --recursive
              shell: bash

            - name: Create Comment
              uses: marocchino/sticky-pull-request-comment@v2
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  number: ${{ steps.pr.outputs.id }}
                  message: '[Preview](https://preview.shbov.ru/${{ steps.pr.outputs.id }}/) is ready.'
