name: PR Preview Deploy

on:
    workflow_run:
        workflows: ['PR Preview Build']
        types:
            - completed

jobs:
    deploy:
        name: Deploy
        if: >
            github.event.workflow_run.event == 'pull_request' &&
            github.event.workflow_run.conclusion == 'success'
        runs-on: ubuntu-latest
        steps:
            - name: Download Artifacts
              uses: actions/download-artifact@v4
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  run-id: ${{ github.event.workflow_run.id }}

            - name: Extract PR Number
              id: pr
              run: echo "::set-output name=id::$(<pr/pr-id.txt)"
              shell: bash

            - name: Install AWS CLI
              uses: unfor19/install-aws-cli-action@v1
              with:
                  version: 2.22.35
                  arch: amd64

            - name: Upload to S3
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.STORYBOOK_S3_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.STORYBOOK_S3_SECRET_KEY }}
                  AWS_DEFAULT_REGION: ru-central1
                  AWS_EC2_METADATA_DISABLED: true
                  AWS_REQUEST_CHECKSUM_CALCULATION: when_required
                  AWS_RESPONSE_CHECKSUM_VALIDATION: when_required
              run: aws s3 cp static s3://storybook-oko-ui/pulls/${{ steps.pr.outputs.id }}/ --endpoint-url=https://storage.yandexcloud.net --recursive
              shell: bash

            - name: Create Comment
              uses: marocchino/sticky-pull-request-comment@v2
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  number: ${{ steps.pr.outputs.id }}
                  message: '[Preview](https://preview.shbov.ru/${{ steps.pr.outputs.id }}/) is ready.'
